name: Publish conventions to GitHub Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run Tests
        uses: bratek20/github-actions/publish-artifacts-action@main
        with:
          module-name: build-logic
          github-token: ${{ secrets.GITHUB_TOKEN }}