name: Publish version catalog to GitHub Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: bratek20/github-actions/publish-artifacts-action@main
        with:
          project-name: version-catalog
          github-token: ${{ secrets.GITHUB_TOKEN }}