name: Publish modules to GitHub Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        uses: bratek20/github-actions/publish-artifacts-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}