name: Run Tests

permissions:
  checks: write
  pull-requests: write
  
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Publish locally version catalog (TODO publish only locally)
        uses: bratek20/github-actions/publish-artifacts-action@main
        with:
          project-name: version-catalog
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        uses: bratek20/github-actions/run-tests-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}