name: Run Tests

permissions:
  checks: write
  pull-requests: write
  
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Testing starter modules
        uses: bratek20/github-actions/run-tests-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing logs modules
        uses: bratek20/github-actions/run-tests-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project: bratek20-logs